# Configuration for Auto Assign - https://github.com/kentaro-m/auto-assign

# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: true

# A list of reviewers to be added to pull requests (GitHub user names)
reviewers:
  - rechain-ide-maintainers
  - rechain-ide-core-team

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 2

# A list of assignees, overrides reviewers if set
assignees:
  - rechain-ide-maintainers

# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 1

# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:
  - wip
  - draft
  - do not merge

# A list of users to be skipped by the auto-assign process
skipUsers:
  - dependabot[bot]
  - renovate[bot]