---
name: General
about: General discussion about the project
title: "[General] "
labels: ["general"]
assignees: ''

---

**Topic**
<!-- What would you like to discuss? -->

**Context**
<!-- Provide background information -->

**Discussion Points**
<!-- What specific points would you like to cover? -->

1. 
2. 
3. 

**Expected Outcome**
<!-- What do you hope to achieve from this discussion? -->
