---
name: Show and Tell
about: Show off what you've built with REChain IDE
title: "[Showcase] "
labels: ["showcase"]
assignees: ''

---

**Project/Use Case**
<!-- What did you build or accomplish? -->

**Description**
<!-- Describe your project or use case in detail -->

**Screenshots/Videos**
<!-- Share screenshots, GIFs, or video links -->

**Technologies Used**
<!-- Which features of REChain IDE did you use? -->

**Challenges Overcome**
<!-- What challenges did you face and how did you solve them? -->

**Code/Resources**
<!-- Link to code, repositories, or other resources if available -->

**Feedback for REChain Team**
<!-- Any suggestions or feedback based on your experience? -->
