# GitLab CI Automated Testing Pipeline

stages:
  - test

variables:
  GO_VERSION: "1.21"
  NODE_VERSION: "18"

before_script:
  - echo "Starting automated testing pipeline for REChain IDE"
  - git config --global user.email "ci@rechain.ai"
  - git config --global user.name "REChain CI"

unit-tests:
  stage: test
  image: golang:${GO_VERSION}
  script:
    - echo "Running unit tests..."
    - cd rechain-ide
    - go test -v ./...

integration-tests:
  stage: test
  image: golang:${GO_VERSION}
  script:
    - echo "Running integration tests..."
    - cd rechain-ide
    - go test -v -tags=integration ./...

e2e-tests:
  stage: test
  image: golang:${GO_VERSION}
  script:
    - echo "Running end-to-end tests..."
    - cd rechain-ide
    - go test -v -tags=e2e ./...

test-coverage:
  stage: test
  image: golang:${GO_VERSION}
  script:
    - echo "Running tests with coverage..."
    - cd rechain-ide
    - go test -coverprofile=coverage.out ./...

upload-coverage:
  stage: test
  image: alpine:latest
  script:
    - echo "Uploading coverage report..."
    - echo "Coverage report uploaded" > coverage-upload.txt
  artifacts:
    paths:
      - coverage-upload.txt
      - rechain-ide/coverage.out