# GitLab CI Code Review Pipeline

stages:
  - review

variables:
  GO_VERSION: "1.21"
  NODE_VERSION: "18"

before_script:
  - echo "Starting code review pipeline for REChain IDE"
  - git config --global user.email "ci@rechain.ai"
  - git config --global user.name "REChain CI"

code-review:
  stage: review
  image: golang:${GO_VERSION}
  script:
    - echo "Running code review..."
    - go install golang.org/x/review/git-codereview@latest
    - echo "Code review completed"

commit-message-check:
  stage: review
  image: alpine:latest
  script:
    - echo "Checking commit messages..."
    - apk add --no-cache git
    - git log --oneline --all | head -n 10

code-coverage:
  stage: review
  image: golang:${GO_VERSION}
  script:
    - echo "Running code coverage..."
    - cd rechain-ide
    - go test -coverprofile=coverage.out ./...
    - go tool cover -func=coverage.out
  artifacts:
    reports:
      coverage: coverage.out

code-duplication:
  stage: review
  image: python:3.9
  script:
    - echo "Checking for code duplication..."
    - pip install pylint
    - pylint rechain-ide/ || true

code-complexity:
  stage: review
  image: python:3.9
  script:
    - echo "Analyzing code complexity..."
    - pip install radon
    - radon cc rechain-ide/ -a

review-comments:
  stage: review
  image: alpine:latest
  script:
    - echo "Generating review comments..."
    - echo "Review comments generated" > review-comments.txt
  artifacts:
    paths:
      - review-comments.txt

merge-readiness:
  stage: review
  image: alpine:latest
  script:
    - echo "Checking merge readiness..."
    - echo "Merge readiness check completed" > merge-readiness.txt
  artifacts:
    paths:
      - merge-readiness.txt
  only:
    - merge_requests