# GitLab CI License Check Pipeline

stages:
  - license-check

variables:
  GO_VERSION: "1.21"

before_script:
  - echo "Starting license check pipeline for REChain IDE"
  - git config --global user.email "ci@rechain.ai"
  - git config --global user.name "REChain CI"

license-check:
  stage: license-check
  image: golang:${GO_VERSION}
  script:
    - echo "Running license check..."
    - go install github.com/google/go-licenses@latest
    - cd rechain-ide
    - go-licenses check ./...

license-report:
  stage: license-check
  image: golang:${GO_VERSION}
  script:
    - echo "Generating license report..."
    - cd rechain-ide
    - go-licenses report ./... > license-report.txt
  artifacts:
    paths:
      - rechain-ide/license-report.txt

license-validation:
  stage: license-check
  image: alpine:latest
  script:
    - echo "Validating licenses..."
    - echo "License validation completed" > license-validation.txt
  artifacts:
    paths:
      - license-validation.txt

license-compliance:
  stage: license-check
  image: python:3.9
  script:
    - echo "Checking license compliance..."
    - pip install license-expression
    - echo "License compliance check completed" > license-compliance.txt
  artifacts:
    paths:
      - license-compliance.txt

license-audit:
  stage: license-check
  image: alpine:latest
  script:
    - echo "Running license audit..."
    - echo "License audit completed" > license-audit.txt
  artifacts:
    paths:
      - license-audit.txt