# GitLab CI Security Scan Pipeline

stages:
  - security-scan

variables:
  GO_VERSION: "1.21"
  NODE_VERSION: "18"

before_script:
  - echo "Starting security scan pipeline for REChain IDE"
  - git config --global user.email "ci@rechain.ai"
  - git config --global user.name "REChain CI"

go-security-check:
  stage: security-scan
  image: golang:${GO_VERSION}
  script:
    - echo "Running Go security check..."
    - cd rechain-ide
    - go install github.com/securego/gosec/v2/cmd/gosec@latest
    - gosec ./...

npm-audit:
  stage: security-scan
  image: node:${NODE_VERSION}
  script:
    - echo "Running npm audit..."
    - cd rechain-ide/vscode-extension/extension
    - npm audit

sast-scan:
  stage: security-scan
  image: golang:${GO_VERSION}
  script:
    - echo "Running SAST scan..."
    - cd rechain-ide
    - go install github.com/praetorian-inc/gokart@latest
    - gokart scan

dependency-check:
  stage: security-scan
  image: golang:${GO_VERSION}
  script:
    - echo "Running dependency check..."
    - cd rechain-ide
    - go install github.com/sonatype-nexus-community/nancy@latest
    - go list -json -m all | nancy sleuth

security-report:
  stage: security-scan
  image: alpine:latest
  script:
    - echo "Generating security report..."
    - echo "# Security Scan Report" > security-report.md
    - echo "Scan completed on $(date)" >> security-report.md
  artifacts:
    paths:
      - security-report.md

upload-security-report:
  stage: security-scan
  image: alpine:latest
  script:
    - echo "Uploading security report..."
    - echo "Security report uploaded" > security-upload.txt
  artifacts:
    paths:
      - security-upload.txt